### ISSUE TITLE
Add `npm stop`, so server can stop and restart gracefully

### ISSUE THREAD

**Issue by mitchhentges** [binder-app/server#5]
We can't use `npm start`, because the returned pid is not the parent of the actual node process. If `npm stop` killed the server properly, then we can fit into the `npm` lifecycle again on the server

**Comment by chrisfosterelli** [comment]
@mitchhentges the "returned pid"? `npm start` shouldn't return anything at all, it shouldn't exit until sent a termination signal. Could you elaborate how you are running this?

**Comment by mitchhentges** [comment]
Exactly. However, when starting and stopping the server, the administrator doesn't "block" on the server, he starts it in the background:

```
node server >server.log 2>server.err &
echo $! > server.pid
```

Later, that admin wants to stop the server. The running process (still hasn't exited), has a pid (in `server.pid`, in this case). He kills the pid, the process stops

**Comment by chrisfosterelli** [comment]
Thanks, that clarifies. I did a bunch of research and if we're going to use an init script then what you described seems like the right way to go.
