### ISSUE TITLE
Should be able to delete records from the database during development

### ISSUE THREAD

**Issue by stevelyall** [binder-app/server#9]
@mitch9654 Since the API doesn't support it, would you mind providing us with SSH/db credentials to run queries on the db during development?

The API responds with suggestions until you've liked or disliked all of them, after which zero results are returned, which is problematic for testing.
Also it would let us clear out some garbage data in there?

**Comment by mitchhentges** [comment]
We changed from `MariaDB` to `RethinkDB`, if you ask Chris nicely he can hook this up.
(@chrisfosterelli, ping me on Slack for when to `-bind all` for you)
